# Generated by Django 3.0.7 on 2020-06-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=150)),
                ('price_tag', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
