# Generated by Django 3.0.7 on 2020-06-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price_tag',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
